application:
  version: v1

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/chaosmin_user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: app_user
    password: bEza26gqbXiVWTy9
  output:
    ansi:
      enabled: always

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted

log:
  access:
    enable: true
  provider:
    enable: true

swagger:
  enable: true
  packages: tech.chaosmin.framework.provider
  contact:
    name: Romani min
    url: http://chaosmin.tech
    email: minchao1029@hotmail.com
    website: http://blog.chaosmin.tech

server:
  global-anonymous: false
  interceptor:
    except:
      - /swagger-ui/**
      - /login