application:
  name: chaosmin-cdpt
  version: v1
  description: 出单平台
  license: Apache License 2.0
  licenseUrl: https://github.com/chaosmin/chaosmin-framework/blob/master/LICENSE

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://rm-uf6e9i0tl60ppsyb61250100m.mysql.rds.aliyuncs.com:3306/chaosmin_cdpt?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: minchao
    password: gqsLFoKh38DlQigI
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  output:
    ansi:
      enabled: always

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted

log:
  access:
    enable: true
  provider:
    enable: true

swagger:
  enable: true
  packages: tech.chaosmin.framework.provider
  contact:
    name: Romani min
    url: http://chaosmin.tech
    email: minchao1029@hotmail.com
    website: http://blog.chaosmin.tech

server:
  global-anonymous: false
  limit:
    permitsPerSecond: 1000
    tps: 1000
    limitType: DROP
  interceptor:
    except:
      - /swagger-ui/**
      - /auth/login